version: "3.9"

services:
  telegram_bot:
    build: ./
    container_name: telegram_bot
    restart: "no"
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      # Монтируем папку для данных бота в текущую директорию проекта
      - ./bot_data:/app/bot_data
